---
title: "Aman Arora"
about:
  template: marquee
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/amaarora
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/aroraaman/
    - icon: github
      text: Github
      href: https://github.com/amaarora
---

Aman Arora is the Data Science Lead at [PropTrack](https://www.proptrack.com.au/). Outside of work, Aman enjoys playing badminton and going for runs along the beach.

Being largely self-taught, Aman dedicates much of his time to staying current with the latest research. He has a strong passion for sharing his knowledge and insights, which he documents on this blog.

## Experience
1. **Data Science Lead,** REA Group, May 2022 – Present 
2. **Machine Learning Engineer,** Weights and Biases, Mar 2021 – May 2022
3. **Applied AI Scientist,** Harrison AI, Nov 2020 – Mar 2021
4. **Data Scientist,** CoreLogic Australia, Mar 2019 – Nov 2020 

## Education
1. **Master of Technology - MTech,** Information Technology, Charles Sturt University
2. **Bachelor of Technology - BTech,** Electrical, Electronics and Communications Engineering, Maharaja Surajmal Institute of Technology
