---
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---

# Index
You will often see me writing about research papers (mostly in the field of Computer Vision) explaining them in a simple language in theory along with their PyTorch Implementation. Please feel free to **[subscribe](https://amaarora.github.io/#subscribe-to-aman-aroras-blog)** to receive regular updates regarding new blog posts.

During my time as Machine Learning Engineer at Weights and Biases, I also wrote the following blog posts:

| Title  | Link  |
|--------|--------|
| Explained: Characterizing Signal Propagation to Close the Performance Gap in Unnormalized ResNets  | [[link](https://wandb.ai/wandb_fc/pytorch-image-models/reports/Explained-Characterizing-Signal-Propagation-to-Close-the-Performance-Gap-in-Unnormalized-ResNets--Vmlldzo2NDIzNTE)]   |
|Revisiting ResNets: Improved Training and Scaling Strategies | [[link](https://wandb.ai/wandb_fc/pytorch-image-models/reports/Revisiting-ResNets-Improved-Training-and-Scaling-Strategies--Vmlldzo2NDE3NTM)]   |
|ConViT: Improving Vision Transformers with Soft Convolutional Inductive Biases | [[link](https://wandb.ai/wandb_fc/pytorch-image-models/reports/ConViT-Improving-Vision-Transformers-with-Soft-Convolutional-Inductive-Biases--Vmlldzo3MjIxMDk?galleryTag=intermediate)]   |
|Is MLP-Mixer a CNN in Disguise?| [[link](https://wandb.ai/wandb_fc/pytorch-image-models/reports/Is-MLP-Mixer-a-CNN-in-Disguise---Vmlldzo4NDE1MTU?galleryTag=intermediate)]   |
|Are fully connected and convolution layers equivalent? If so, how?| [[link](https://wandb.ai/wandb_fc/pytorch-image-models/reports/Are-fully-connected-and-convolution-layers-equivalent-If-so-how---Vmlldzo4NDgwNjY)]   |
|A faster way to get working and up-to-date conda environments using "fastchan"| [[link](https://wandb.ai/wandb_fc/pytorch-image-models/reports/A-faster-way-to-get-working-and-up-to-date-conda-environments-using-fastchan---Vmlldzo2ODIzNzA)]   |
|Inside Hugging Face's Accelerate!| [[link](https://wandb.ai/wandb_fc/pytorch-image-models/reports/Inside-Hugging-Face-s-Accelerate---Vmlldzo2MzgzNzA)]   |

: Previous blog posts {tbl-colwidths="[75,25]"}


<!-- Add a line break -->
+-------+-------------+
|       |             |
+-------+-------------+